#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
# I do not know why those URLs fail the proofer, they do exist. :/
bundle exec htmlproofer ./public --url-ignore "/^mailto:/,/code.gov\/about\/open-source\/introduction/,/code.gov\/about\/compliance\/inventory-code/,/twitter.com\/DefenseDigital/"
